name: ci-test

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:

    build:
        name: Test
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                ports:
                    - 5432:5432
                env:
                    POSTGRES_USER: root
                    POSTGRES_PASSWORD: secret
                    POSTGRES_DB: simple_bank
                # Set health check to wait for postgres to start
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:

        - name: Set up Go 1.23
          uses: actions/setup-go@v2
          with:
            go-version: 1.23
          id: go

        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Run migrations
          run: make migrateup

        - name: Test
          run: make testCI